### ISSUE TITLE
Combine with golang action

### ISSUE THREAD

**Issue by r03** [numworks/setup-msys2#13]
How can I combine this action with golang?
The command `go env` works, but `msys2do go env` doesn't.

```
name: msys2 build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-go@v1
      - uses: numworks/setup-msys2@v1

      - uses: actions/checkout@v1

      - run: go env
      - run: msys2do go env

```

```
D:\a\project\project>d:\a\_temp\msys\\msys64\usr\bin\bash.exe -ilc "cd $OLDPWD && go env" 
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: go: command not found
##[error]Process completed with exit code 1.
```

**Comment by 1138-4EB** [comment]
This is the *expected* behaviour, because `MSYS2_PATH_TYPE` is set to `strict`: https://github.com/numworks/setup-msys2/blob/master/index.js#L38. If set to `inherit`, it works. You can test it by forking this repo, changing that line and running the following workflow:

```yml
name: go
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v1
      - uses: actions/checkout@v1
      - run: yarn
      - uses: ./
      - run: msys2do go env
```

- https://github.com/msys2/msys2/wiki/MSYS2-introduction#path
- https://github.com/msys2/MSYS2-packages/commit/7fd131dde0be023ac0516cbc6bed1eed6f77295c
