### ISSUE TITLE
How to add gcc and add it to PATH?

### ISSUE THREAD

**Issue by liudonghua123** [numworks/setup-msys2#31]
Hi, I just want to build something under Windows using msys2's gcc. From the docs, I didn't find how can I install gcc and releated toolchains and add these binary to the PATH, and make them avaliable in the following steps?

**Comment by Ecco** [comment]
```yaml
  build-simulator-windows:
    runs-on: windows-latest
    steps:
      - uses: numworks/setup-msys2@v1
      - uses: actions/checkout@v1
      - run: msys2do pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-freetype mingw-w64-x86_64-pkg-config make
      - run: msys2do make
```

You can replace the last line with `msys2do mingw-w64-x86_64-gcc whatever` :)
